app:
    url: http://localhost:3000
    #url: http://6a93b90a.ngrok.io
db:
    url: mongodb://localhost/fedo
analytics:
    enable: true
    apiToken: 59e2ecc34d1297d7e784664939fe125f
mail:
    mailer:
        apiKey: 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
    from: reviews@outreech.com
    fromName: Team Outreech
integrations:
    shopify:
        app_uri: https://83e3f6c1.ngrok.io/integrations/shopify/install
        redirect_uri: https://83e3f6c1.ngrok.io/integrations/shopify/connect
        apiKey: 1f497a56628f0518250ddfca6db18e57
        apiSecret: 02b709a231505b66b05481f40f4b80b7
        scope:
            - read_products

