app:
    url: http://localhost:3000
db:
    url: mongodb://localhost/fedo
analytics:
    enable: true
    apiToken: 59e2ecc34d1297d7e784664939fe125f
mail:
    mailer:
        apiKey: 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
    from: reviews@outreech.com
    fromName: Team Outreech
